name: Build and deploy container app to Azure Web App - bikesite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to your Docker registry
      run: docker login -u justseppe14 -p ${{ secrets.YourDockerRegistry_Password }}

    - name: Build and push container image to your Docker registry
      run: |
        docker build -t justseppe14/webpage:${{ github.sha }} .
        docker push justseppe14/webpage:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bikesite'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_22bb4cd01c3848c38ecc3ccd8db48306 }}
        images: 'justseppe14/webpage:${{ github.sha }}'
